name: Hello World
author: Roger Canann
description: Some description
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Roger
outputs:
  time:
    description: "The greeting time"
runs:
  using: node12
  main: index.js
